
// This file has been generated by the GUI designer. Do not modify.
namespace GtkSharpTest
{
	public partial class LogViewWidget
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label labelLogName;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textviewLogContents;
		
		private global::Gtk.Button buttonReadLog;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GtkSharpTest.LogViewWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GtkSharpTest.LogViewWidget";
			// Container child GtkSharpTest.LogViewWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelLogName = new global::Gtk.Label ();
			this.labelLogName.Name = "labelLogName";
			this.labelLogName.LabelProp = global::Mono.Unix.Catalog.GetString ("Log name");
			this.vbox1.Add (this.labelLogName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelLogName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewLogContents = new global::Gtk.TextView ();
			this.textviewLogContents.CanFocus = true;
			this.textviewLogContents.Name = "textviewLogContents";
			this.textviewLogContents.Editable = false;
			this.textviewLogContents.WrapMode = ((global::Gtk.WrapMode)(1));
			this.GtkScrolledWindow.Add (this.textviewLogContents);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.buttonReadLog = new global::Gtk.Button ();
			this.buttonReadLog.CanFocus = true;
			this.buttonReadLog.Name = "buttonReadLog";
			this.buttonReadLog.UseUnderline = true;
			this.buttonReadLog.Label = global::Mono.Unix.Catalog.GetString ("Read log");
			this.vbox1.Add (this.buttonReadLog);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.buttonReadLog]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonReadLog.Clicked += new global::System.EventHandler (this.OnButtonReadLogClicked);
		}
	}
}
